# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  CS_ORG: 'globex-innovations'
  CS_REPO: 'acme-nonprod'
  CS_SERVICE_SLUG: 'ci_acme_service'   # Cloudsmith service account slug
  CS_PROVIDER_URL: 'https://vstoken.dev.azure.com/BotConsulting/'  # Issuer you configured in Cloudsmith

steps:
- checkout: self

# (Optional) Show the ADO OIDC provider URL you can call
- bash: |
    echo "System OIDC Provider URL:"
    echo "$(System.OidcRequestUri)"
    echo
    echo "With API version + audience=cloudsmith:"
    echo "$(System.OidcRequestUri)?api-version=7.1&audience=cloudsmith"
  displayName: "Print OIDC provider URL (info)"

- bash: |
    set -euo pipefail

    OIDC_TOKEN=$(curl -s -X POST \
      -H "Authorization: Bearer $(System.AccessToken)" \
      -H "Content-Length: 0" \
      "$(System.OidcRequestUri)?api-version=7.1&audience=cloudsmith" \
      | jq -r '.oidcToken')

    [ -n "$OIDC_TOKEN" ] && [ "$OIDC_TOKEN" != "null" ] || { echo "Failed to mint ADO OIDC token"; exit 1; }

    # (Optional) Inspect, but don't fail the step if decode complains about padding
    echo "$OIDC_TOKEN" | awk -F. '{print $2}' | base64 -d 2>/dev/null | jq '{iss,aud,sub}' || true

    CSM_TOKEN=$(curl -s -X POST \
      -H "Content-Type: application/json" \
      -d "{\"oidc_token\":\"$OIDC_TOKEN\",\"service_slug\":\"$(CS_SERVICE_SLUG)\"}" \
      "https://api.cloudsmith.io/openid/$(CS_ORG)/" \
      | jq -r '.token')

    [ -n "$CSM_TOKEN" ] && [ "$CSM_TOKEN" != "null" ] || { echo "Failed to obtain Cloudsmith token"; exit 1; }

    echo "##vso[task.setvariable variable=CLOUDSMITH_API_KEY;issecret=true]$CSM_TOKEN"
  displayName: "Mint Cloudsmith token via ADO OIDC"
