# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

variables: 
  - group: 'Cloudsmith Secure Variables' # variable group

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- bash:  |
    python -m pip install --upgrade pip
    pip install -r requirements.txt --index-url https://$CS_SERVICE:$CS_API_KEY@dl.cloudsmith.io/basic/globex-innovations/acme-nonprod/python/simple/ 
  displayName: 'Install dependencies'
  env:
    CS_API_KEY: $(APIKey)
    CS_SERVICE: $(ServiceName)


- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
