# azure-pipelines.yml
trigger:
- main

pool:
   vmImage: ubuntu-latest
# pool:
#   vmImage: 'windows-latest'

variables:
  # ---- Cloudsmith settings ----
  CS_WORKSPACE: 'globex-innovations'
  CS_REPO: 'acme-nonprod'
  CS_SERVICE_SLUG: 'ci_acme_service'   # service account slug (username for Basic Auth)

steps:
- checkout: self

# ===== Cloudsmith: authenticate via native ADO OIDC (no CLI install) =====
# This exchanges the ADO OIDC token for a short-lived Cloudsmith API key.
#- task: CloudsmithCliInstallAndAuthenticate@1
- task: CloudsmithCliInstallAndAuthenticate@1

  displayName: "Cloudsmith: Authenticate via OIDC (no Entra)"
  inputs:
    authMethod: 'oidc'
    oidcAuthOnly: true        # just auth; skip CLI install
    pipInstall: false
    cliVersion: ''            # ignored when oidcAuthOnly=true
    oidcNamespace: '$(CS_WORKSPACE)'
    oidcServiceSlug: '$(CS_SERVICE_SLUG)'

# ===== Python: install deps from Cloudsmith =====
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
  displayName: "Use Python 3.12"

- bash: |
    set -eo pipefail
    python -m pip install --upgrade pip
    pip install -r requirements.txt \
      --index-url "https://${CS_SERVICE_SLUG}:${CLOUDSMITH_API_KEY}@dl.cloudsmith.io/basic/${CS_WORKSPACE}/${CS_REPO}/python/simple/"
  displayName: "pip install from Cloudsmith"
  env:
    CS_WORKSPACE: $(CS_WORKSPACE)
    CS_REPO: $(CS_REPO)
    CS_SERVICE_SLUG: $(CS_SERVICE_SLUG)
    CLOUDSMITH_API_KEY: $(CLOUDSMITH_API_KEY)   # set by the Cloudsmith task above
