# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  # ---- Cloudsmith settings ----
  CS_WORKSPACE: 'globex-innovations'   # was CS_ORG
  CS_REPO: 'acme-nonprod'
  CS_SERVICE_SLUG: 'ci_acme_service'   # service account slug (username for Basic Auth)

  # ---- npm scope (change to your real scope, e.g., @acme) ----
  NPM_SCOPE: '@your-scope'
  # Optional: a single package to fetch explicitly after npm ci
  NPM_SINGLE_PACKAGE: '@your-scope/some-package@latest'

# Define CLOUDSMITH_API_KEY as a SECRET variable in the pipeline UI/Library (do NOT hardcode)

steps:
- checkout: self

# ===== Python: install deps from Cloudsmith =====
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
  displayName: "Use Python 3.12"

- bash: |
    set -eo pipefail
    python -m pip install --upgrade pip
    pip install -r requirements.txt \
      --index-url "https://${CS_SERVICE_SLUG}:${CLOUDSMITH_API_KEY}@dl.cloudsmith.io/basic/${CS_WORKSPACE}/${CS_REPO}/python/simple/"
  displayName: "pip install from Cloudsmith"
  env:
    CS_WORKSPACE: $(CS_WORKSPACE)
    CS_REPO: $(CS_REPO)
    CS_SERVICE_SLUG: $(CS_SERVICE_SLUG)
    CLOUDSMITH_API_KEY: $(CLOUDSMITH_API_KEY)   # secret

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: "Use Node.js 20"

- bash: |
    set -eo pipefail
    npm --version

    # Configure scoped registry + auth token
    npm config set ${NPM_SCOPE}:registry "https://npm.cloudsmith.io/${CS_WORKSPACE}/${CS_REPO}/"
    npm config set //npm.cloudsmith.io/${CS_WORKSPACE}/${CS_REPO}/:_authToken="${CLOUDSMITH_API_KEY}"

    # Install project deps from package-lock.json
    npm ci

    # (Optional) fetch one explicit package from your registry to verify connectivity
    if [ -n "${NPM_SINGLE_PACKAGE}" ]; then
      npm install "${NPM_SINGLE_PACKAGE}"
    fi

    # Optional: audit (works with API key)
    npm audit || true
  displayName: "npm install from Cloudsmith (scoped)"
  env:
    CS_WORKSPACE: $(CS_WORKSPACE)
    CS_REPO: $(CS_REPO)
    CLOUDSMITH_API_KEY: $(CLOUDSMITH_API_KEY)
    NPM_SCOPE: $(NPM_SCOPE)
    NPM_SINGLE_PACKAGE: $(NPM_SINGLE_PACKAGE)
