trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    set -euo pipefail

    # 1) Request an ADO OIDC JWT (requires "Allow scripts to access OAuth token")
    token=$(curl -sSf "$(System.OidcRequestUri)?api-version=7.1" \
      -H "Authorization: Bearer $(System.AccessToken)" | jq -r '.token')

    # 2) Extract payload (2nd segment), convert base64url->base64, add padding, decode
    payload=$(echo "$token" | cut -d '.' -f2)
    payload=$(echo "$payload" | tr '-_' '+/')                       # urlsafe -> std
    pad=$(( (4 - ${#payload} % 4) % 4 )); payload="${payload}$(printf '=%.0s' $(seq 1 $pad))"
    claims=$(echo "$payload" | base64 -d 2>/dev/null)

    # 3) Print the bits you need for Cloudsmith OIDC setup
    echo "Issuer (iss) – use this as the Provider URL in Cloudsmith:"
    echo "$claims" | jq -r '.iss'
    echo "Audience (aud):"
    echo "$claims" | jq -r '.aud'
  displayName: "Print ADO OIDC issuer/audience"

