# azure-pipelines.yml
# Build & test a Python package using a Cloudsmith private index

trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: UsePythonVersion@0
  displayName: "Use Python $(python.version)"
  inputs:
    versionSpec: '$(python.version)'
    addToPath: true

- bash: |
    set -euo pipefail
    python -m pip install --upgrade pip
    # Install from Cloudsmith (org/repo: globex-innovations/acme-nonprod)
    pip install -r requirements.txt \
      --index-url "https://${CS_SERVICE}:${CS_API_KEY}@dl.cloudsmith.io/basic/globex-innovations/acme-nonprod/python/simple/"
  displayName: "Install dependencies"
  env:
    CS_API_KEY: $(CS_API_KEY)
    CS_SERVICE: $(CS_SERVICE)

- bash: |
    set -euo pipefail
    pip install pytest pytest-azurepipelines
    pytest
  displayName: "Run tests"
