name: Terraform

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

permissions:
  contents: read
  id-token: write  # Necessary for GH Identity Provider to write the JWT token which Cloudsmith needs to read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0  # Specify the desired Terraform version

      - name: Authenticate to Cloudsmith using OIDC
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.0
        with:
          oidc-namespace: ciara-demo  # Your Cloudsmith organization slug
          oidc-service-slug: gh-service  # Use the already created service account

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
